onboarding = false

[ui.toast]
delivery = "herdr"

[ui]
status_indicators = "symbols"
redraw_on_focus_gained = false
pane_scrollbars = false

[update]
version_check = false
manifest_check = false

[terminal]
default_shell = "C:\\Users\\chberger\\.dotfiles\\cmder\\cmder-shell.cmd"

[keys]
# Note that the following keybindings are handled via the `herdr_navigation.ahk` script on Windows
# focus_pane_left = ["ctrl+h", "prefix+h"]
# focus_pane_down = ["ctrl+j", "prefix+j"]
# focus_pane_up = ["ctrl+k", "prefix+k"]
# focus_pane_right = ["ctrl+l", "prefix+l"]

# Note that the following keybindings (ctrl+shift+... version) are note working natively on Winodws Terminal!
# This, they are also handled via the herdr CLI in the `herdr_navigation.ahk` script on Windows.
resize_pane_left = ["ctrl+shift+h", "prefix+shift+h"]
resize_pane_down = ["ctrl+shift+j", "prefix+shift+j"]
resize_pane_up = ["ctrl+shift+k", "prefix+shift+k"]
resize_pane_right = ["ctrl+shift+l", "prefix+shift+l"]

previous_tab = ["alt+h", "prefix+p"]
next_tab = ["alt+l", "prefix+n"]

previous_workspace = "alt+k"
next_workspace = "alt+j"

split_vertical = ["prefix+v", "ctrl+alt+d"]
split_horizontal = ["prefix+h", "ctrl+alt+shift+d"]
