gui:
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  scrollHeight: 3 # how many lines you scroll by
  scrollOffMargin: 5 # how many lines to keep before/after the cursor when it reaches the top/bottom of the view; see 'Scroll-off Margin' section below
  shortTimeFormat: '15:04'
  statusPanelView: 'allBranchesLog' # always show git graph in status view
  timeFormat: '02 Jan 06' # https://pkg.go.dev/time#Time.Format
  theme: # Catppuccin Mocka Theme w/ Blue Accent
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    # - externalDiffCommand: difft --color=always --display=inline
    # - useExternalDiffGitConfig: true # use external diff command as configured in git (`diff.external`)
    # - externalDiffCommand: "C:/Users/chberger/.dotfiles/lazygit/config/lazygit-pager.cmd"
    - externalDiffCommand: "C:/Users/chberger/.dotfiles/lazygit/config/lazygit-pager.ps1"
  log:
    order: 'date-order'
    showGraph: 'always'
    showWholeGraph: true
  mainBranches: [master, main, dev]
notARepository: 'prompt' # one of: 'prompt' | 'create' | 'skip' | 'quit'
customCommands:
  - key: 'B'
    context: 'global'
    command: 'git pull --rebase'
