# -----------------------------------------------------------------------------
# Powerlevel10k Instant Prompt (must be at the top)
# -----------------------------------------------------------------------------
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# -----------------------------------------------------------------------------
# Oh-My-Zsh Core Setup
# -----------------------------------------------------------------------------
if [[ -d "$HOME/.oh-my-zsh" ]]; then
    export ZSH="$HOME/.oh-my-zsh"
else
    export ZSH="/usr/share/oh-my-zsh"
fi

# Default editor
export EDITOR="nvim"

# SSH Agent socket
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"


# -----------------------------------------------------------------------------
# Zsh Behavior Settings
# -----------------------------------------------------------------------------
DISABLE_MAGIC_FUNCTIONS="true"    # Fix pasting glitches
ENABLE_CORRECTION="true"          # Auto-correct mistyped commands
HYPHEN_INSENSITIVE="true"         # treat - and _ the same
COMPLETION_WAITING_DOTS="true"    # show dots during slow completions


# -----------------------------------------------------------------------------
# Theme (Powerlevel10k)
# -----------------------------------------------------------------------------
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# Load your personal p10k config if present
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh


# -----------------------------------------------------------------------------
# Oh-My-Zsh Plugins
# -----------------------------------------------------------------------------
# Only set plugins if not already defined
[[ -z "${plugins[*]}" ]] && plugins=(git fzf extract)

source $ZSH/oh-my-zsh.sh


# -----------------------------------------------------------------------------
# History Settings
# -----------------------------------------------------------------------------
export HISTCONTROL=ignoreboth                            # no leading-space cmds, no dups
export HISTIGNORE="&:[bf]g:c:clear:history:exit:reboot:q:pwd:* --help"
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"       # share history between sessions


# -----------------------------------------------------------------------------
# User Aliases
# -----------------------------------------------------------------------------
[[ -f ~/.aliases.zsh ]] && source ~/.aliases.zsh


# -----------------------------------------------------------------------------
# Syntax Highlighting & Suggestions
# -----------------------------------------------------------------------------
# Must be *after* oh-my-zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh


# -----------------------------------------------------------------------------
# Command-not-found handler (Arch pkgfile)
# -----------------------------------------------------------------------------
source /usr/share/doc/pkgfile/command-not-found.zsh


# -----------------------------------------------------------------------------
# Completions & alias expansion
# -----------------------------------------------------------------------------
autoload -Uz compinit && compinit
bindkey "^Xa" _expand_alias

zstyle ':completion:*' completer _expand_alias _complete _ignored
zstyle ':completion:*' regular true


# -----------------------------------------------------------------------------
# Optional Tools
# -----------------------------------------------------------------------------
# fzf
[[ -f $HOME/.fzf.zsh ]] && source $HOME/.fzf.zsh

# zoxide
eval "$(zoxide init zsh)"

# pyenv (disabled)
# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

