# -----------------------------------------------------------------------------
# Powerlevel10k Instant Prompt (must be at the top)
# -----------------------------------------------------------------------------
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# -----------------------------------------------------------------------------
# Oh-My-Zsh Core Setup
# -----------------------------------------------------------------------------
if [[ -d "$HOME/.oh-my-zsh" ]]; then
    export ZSH="$HOME/.oh-my-zsh"
else
    export ZSH="/usr/share/oh-my-zsh"
fi

# Default editor
export EDITOR="nvim"

# SSH Agent socket
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"


# -----------------------------------------------------------------------------
# Zsh Behavior Settings
# -----------------------------------------------------------------------------
DISABLE_MAGIC_FUNCTIONS="true"    # Fix pasting glitches
ENABLE_CORRECTION="true"          # Auto-correct mistyped commands
HYPHEN_INSENSITIVE="true"         # treat - and _ the same
COMPLETION_WAITING_DOTS="true"    # show dots during slow completions


# -----------------------------------------------------------------------------
# Theme (Powerlevel10k)
# -----------------------------------------------------------------------------
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# Load your personal p10k config if present
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh


# -----------------------------------------------------------------------------
# Oh-My-Zsh Plugins
# -----------------------------------------------------------------------------
# Only set plugins if not already defined
[[ -z "${plugins[*]}" ]] && plugins=(git fzf extract)

# plugins=(
#   git
#   zsh-vi-mode
#   zsh-autosuggestions
#   fzf-tab
#   zsh-syntax-highlighting
# )

source $ZSH/oh-my-zsh.sh


# -----------------------------------------------------------------------------
# History Settings
# -----------------------------------------------------------------------------
export HISTCONTROL=ignoreboth                            # no leading-space cmds, no dups
export HISTIGNORE="&:[bf]g:c:clear:history:exit:reboot:q:pwd:* --help"
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"       # share history between sessions


# -----------------------------------------------------------------------------
# User Aliases
# -----------------------------------------------------------------------------
[[ -f ~/.aliases.zsh ]] && source ~/.aliases.zsh


# -----------------------------------------------------------------------------
# Syntax Highlighting & Suggestions
# -----------------------------------------------------------------------------
# Must be *after* oh-my-zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh


# -----------------------------------------------------------------------------
# Command-not-found handler (Arch pkgfile)
# -----------------------------------------------------------------------------
source /usr/share/doc/pkgfile/command-not-found.zsh


# -----------------------------------------------------------------------------
# Completions & alias expansion
# -----------------------------------------------------------------------------
autoload -Uz compinit && compinit
bindkey "^Xa" _expand_alias

zstyle ':completion:*' completer _expand_alias _complete _ignored
zstyle ':completion:*' regular true

zstyle ':completion:*' completer _complete _ignored _expand_alias # Select completion types and order
zstyle ':completion:*' menu select # Enable menu opening with tab
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # Ignore caes in completions
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS} # Use LS colors for completion lists

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

# Enable preview
zstyle ':fzf-tab:*' fzf-preview '
  if [[ -d $realpath ]]; then
    ls -lh --color=always $realpath
  else
    bat --style=numbers --color=always $realpath 2>/dev/null || cat $realpath
  fi
'

# ---- zsh-vi-mode hook ----
function zvm_after_init() {

    # ---- fzf ----
    source <(fzf --zsh)
    # export FZF_DEFAULT_OPTS="--height=40% --layout=reverse --border"

    # ---- zoxide ----
    eval "$(zoxide init zsh)"

}

