;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
clear=cls
e.=explorer .
e=explorer $*
dc=doublecmd.exe --no-splash --client -T -path $*
dcr=doublecmd.exe --no-splash --client -T -P R -R $*
dcl=doublecmd.exe --no-splash --client -T -P L -L $*
v=nvim $*
vi=nvim $*
vim=nvim $*
unalias=alias /d $1
editalias=nvim %CMDER_ROOT%\config\user_aliases.cmd & alias /reload
editprofile=nvim %CMDER_ROOT%\config\user_profile.cmd
cmderr=cd /d "%CMDER_ROOT%"
edit=notepad++ $*
calc=ipy -c "from math import *; print($*)"
ls=exa --group-directories-first -F $*
la=exa --group-directories-first -aF $*
ll=exa --group-directories-first -alF $*
l=exa --group-directories-first -alF $*
lr=tree /F $*
cd~=cd "%USERPROFILE%\$*"
gs=git status --short $*
gd=git diff $*
gds=git diff --staged $*
ga=git add $*
gc=git commit -m "$*"
gca=git commit --amend --no-edit
gp=git push $*
gpl=git pull $*
gl=git log --oneline --all --graph --decorate  $*
serial=plink -serial \\.\COM$1 -sercfg $2,8,1,N,N $3 $4 $5 $6 $7 $8 $9
lp=pnputil /enum-devices /class Ports /connected | findstr "COM"
path=echo %path:;=&echo.%
err=echo %ERRORLEVEL%
robot=python -m robot $*
rebot=python -m rebot $*
pipupdateall=pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
wdocker=wsl docker $*
stree=%USERPROFILE%\AppData\Local\SourceTree\SourceTree.exe -f %CD% log
lg=lazygit $*
grep=rg $*
